#ifndef __PI4_CONFIG_H
#define __PI4_CONFIG_H
#include <linux/sizes.h>

/* Physical memory map */
#define CONFIG_SYS_SDRAM_BASE		0x01000000

/* The DTB generated by QEMU is placed at start of RAM, stay away from there */
#define CONFIG_SYS_INIT_SP_ADDR         (CONFIG_SYS_SDRAM_BASE + SZ_2M)
#define CONFIG_SYS_LOAD_ADDR		(CONFIG_SYS_SDRAM_BASE + SZ_2M)
#define CONFIG_SYS_MALLOC_LEN		SZ_16M

/* For timer, QEMU emulates an ARMv7/ARMv8 architected timer */
#define CONFIG_SYS_HZ                       1000

/* Environment options */
#define CONFIG_ENV_ADDR			0x4000000
#define CONFIG_ENV_SIZE			SZ_256K

#define CONFIG_SYS_MONITOR_BASE		CONFIG_SYS_TEXT_BASE
#ifdef CONFIG_TFABOOT
#define CONFIG_SYS_FLASH_BASE		0x4000000
#define CONFIG_SYS_MAX_FLASH_BANKS	1
#else
#define CONFIG_SYS_FLASH_BASE		0x0
#define CONFIG_SYS_MAX_FLASH_BANKS	2
#endif
#define CONFIG_SYS_MAX_FLASH_SECT	256 /* Sector: 256K, Bank: 64M */
#endif /* __PI4_CONFIG_H */
